name: Codegen Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codegen-test:
    name: SDK Codegen Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.19]
    env:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
    steps:
    - uses: actions/checkout@v2

    - name: Download Coretto 17 JDK
      run: |
        download_url="https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz"
        wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

    - name: Set up Coretto 17 JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/java_package.tar.gz
        java-version: 17
        architecture: x64

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: SDK Codegen
      run: cd codegen && ./gradlew clean build -Plog-tests

